### ISSUE TITLE
self.bottom interpretation

### ISSUE THREAD

**Issue by themadpsychologist** [ohadcn/snbopen#6]
I figured out how to split the `style` argument from the `imagePoss` class into its different elements, but I am a bit confused as to what line 99 is trying to accomplish. As it is, it seems to start with 841.89, add the "height" attribute, and subtract the "mso-position-horizontal-relative" attribute, which has no numerical value. Is this correct? Also, what does the number 841.89 represent?

Reply if convenient; otherwise, I'll try to work it out myself.
Many thanks!

**Comment by ohadcn** [comment]
I haven't touched the code in a while, nor having Samsung notebooks any more.
but I guess that SNB is positioning the image from the **top** - left position, while reportlab positioned the image from the **bottom** - left position, and the mentioned code is intended to convert one representation to another.

**Comment by themadpsychologist** [comment]
Many thanks!

**Comment by themadpsychologist** [comment]
Thank you for making this project! I dropped my intended update of it, but wrote a module to convert SNB to TXT instead, crediting you for inspiration in the README.

By the way, I'll soon be looking for work, if I can get it. I know little Python and nothing else, but I learn quickly, and now I know some basics of zipfile and os. Let me know if you can use me for anything!
